### ISSUE TITLE
有关编译问题？

### ISSUE THREAD

**Issue by CalvinRui** [DreamHacks/dreamdota#2]
你好。非常感谢上传此项目源码！代码编译过程中出现好多错误，另外头文件有部分不完整，打开项目中一个txt文档是编译须知，但是没有此文件，麻烦能帮忙上传一下完整的吗？万分感谢！

**Comment by fluxxu** [comment]
你好，这个就是完整的。。。
你编译之前装python 2.x了吗？
缺什么文件？
@thewisp
你还记得怎么编译吗？

**Comment by CalvinRui** [comment]
非常感谢你的回复，没有安装python 2.x，我先下载安装再试试。请问能留一下邮箱联系方式吗？谢谢你~

**Comment by CalvinRui** [comment]
SVN_info.h这个文件缺失哦

**Comment by CalvinRui** [comment]
1>  UnicodeEncodeError: 'ascii' codec can't encode characters in position 104-107: ordinal not in range(128)
1>  "Generating Revision info..."
1>  'SubWCRev.exe' 不是内部或外部命令，也不是可运行的程序
1>  或批处理文件。
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: 命令“IF EXIST pre_build.cmd pre_build.cmd "I:\项目\DOTA\DOTA全图源码\VC全图源码\DreamDota3\dreamdota-master\DreamWarcraft\" "I:\项目\DOTA\DOTA全图源码\VC全图源码\DreamDota3\dreamdota-master\Release\DreamWarcraft.dll"  "I:\项目\DOTA\DOTA全图源码\VC全图源码\DreamDota3\dreamdota-master\Release\" "DreamWarcraft.dll"
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :VCEnd”已退出，代码为 1。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by CalvinRui** [comment]
安装了python 2.x，还是出现很多错误， 各种未声明的标示符，还有缺失SVN_info.h文件哦，源码不完整吧应该，用VS 2010编译的，请指点一下如何完整编译呢？还是源码不完整呢？

**Comment by fluxxu** [comment]
这个项目曾经是用svn管理的，这个svn的依赖是为了自动获取svn revision的。
现在既然已经搬到github这个就没有用了。
这个项目我们现在已经没有时间维护了，你可以修改一下去掉svn的依赖。
最好修改好了给我们一个pull request。
多谢。
