### ISSUE TITLE
有关功能测试三个问题,请求帮忙指点一下

### ISSUE THREAD

**Issue by CalvinRui** [DreamHacks/dreamdota#3]
你好，经过修改去掉了SVN的依赖，经过编译以后，发现有如下三个问题：
1，数字显示血蓝问题，开启后游戏直接崩溃
2，自定义热键面板显示不出来
3，左上角的信息面板，选择DOTA会崩溃

以上三个问题帮忙回复指点一下，谢谢你！修改好以后我会pull requests
@fluxxu @TheWisp

**Comment by TheWisp** [comment]
直接编译出的dll是不带资源文件的，而有贴图等资源文件是post build 合并进文件的。你找找output文件夹里应该有合并后的dll，而不是项目编译直接输出的dll。

**Comment by fluxxu** [comment]
补充一下，我们是把我们用到的额外资源打包进一个MPQ文件，直接附加到了DLL文件的后面，然后在游戏里面调用Storm Lib加载的。
打包好的DLL应该在LastBuildOutput文件夹里面。

post build合并代码是这个：
https://github.com/DreamHacks/dreamdota/blob/master/DreamWarcraft/post_build.cmd#L10

游戏里面调用的代码是这个：
https://github.com/DreamHacks/dreamdota/blob/eea45584d62a243805a490add9f044be6c1fd483/DreamWarcraft/MPQ.cpp#L13

**Comment by CalvinRui** [comment]
感谢两位的指点，经过你们的指点现在已经成功编译，功能完整，近期发现有一个插件和这个是一样的，那个还能显示船长水，卡尔天火，白牛C，是不是我们这个源码还有更新版本呢？

**Comment by CalvinRui** [comment]
感谢两位的指点，经过你们的指点现在已经成功编译，功能完整，近期发现有一个插件和这个是一样的，那个还能显示船长水，卡尔天火，白牛C，是不是我们这个源码还有更新版本呢？能否发出来我整合一起后在pull request上来呢？ @TheWisp @fluxxu

**Comment by fluxxu** [comment]
能编译就好。

**Comment by fluxxu** [comment]
你说的变种有可能是之前得到代码的人进行的二次开发。我们官方自2012后就没有更新新功能。除了 @thewisp 为直播做的修改和对vs2015的支持。
