### ISSUE TITLE
Using UI in mainmenu ? 

### ISSUE THREAD

**Issue by Karaulov** [DreamHacks/dreamdota#6]
How to create SimpleFrame in MainMenu?

Any example? I found only change version text :(

**Comment by fluxxu** [comment]
I don't think these UI components work in MainMenu. 
The UI Module only initialize after a game started:
https://github.com/DreamHacks/dreamdota/blob/eea45584d62a243805a490add9f044be6c1fd483/DreamWarcraft/Game.cpp#L80

For examples of how to use it in game
See
https://github.com/DreamHacks/dreamdota/blob/master/DreamWarcraft/InfoPanelPanel.h
https://github.com/DreamHacks/dreamdota/blob/master/DreamWarcraft/DebugPanel.h

@TheWisp

**Comment by Karaulov** [comment]
I try to use DreamDota for making new menus in Warcraft (not in game).

This is impossible ?

Only LayoutFrame and TextFrame can be used for "non-simpleframes" ?

**Comment by TheWisp** [comment]
Based on the way UI system works - both in-game and lobby use .fdf to create UI widgets I guess it is possible. At the time we had not implemented that into dreamdota though. The lobby UI system should be deeply connected with the in-game ones, maybe share the same base class and therefore the same base vtable. So looking at some of virtual functions would be a good start.

**Comment by Karaulov** [comment]
@TheWisp @fluxxu you can't release clean DreamUI ?:) (Only UI functions without hack functions)

I tried cut all another functions not allways got fail...

**Comment by Karaulov** [comment]
https://github.com/Karaulov/WarcraftIII_DLL_126-127/tree/WarcraftIII_DLL/DreamUI

I remove all maphack features :)
