### ISSUE TITLE
求开源DreamDota 1

### ISSUE THREAD

**Issue by CalvinRui** [DreamHacks/dreamdota#7]
求开源DreamDota 1，因为1有躲避技能等功能，目前发现某宝各种出售此开源项目的辅助，我希望能将此项目整合后免费发出来给大家学习研究 ，抵制某宝盗用此项目进行商业用途，希望作者能够开源出来我们一起抵制这些行为！ @TheWisp @fluxxu

**Comment by luciouskami** [comment]
这就是123

**Comment by fluxxu** [comment]
#5
